/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Získat seznam všech událostí
         * @description Vrací seznam všech dostupných událostí
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Seznam událostí */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventsListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Vytvořit novou událost
         * @description Vytvoří novou událost s možnými termíny
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEventRequest"];
                };
            };
            responses: {
                /** @description Událost byla úspěšně vytvořena */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateEventResponse"];
                    };
                };
                /** @description Neplatná data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Získat detail události podle ID
         * @description Vrací detail konkrétní události včetně všech hlasování
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID události */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detail události */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"];
                    };
                };
                /** @description Událost nebyla nalezena */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserRecord: {
            /** @description Jméno účastníka */
            name: string;
            /**
             * @description Odpověď účastníka na daný termín
             * @enum {string}
             */
            answer: "yes" | "no" | "if-needed";
        };
        DateRecord: {
            /** @description Timestamp termínu v milisekundách */
            timestamp: number;
            /** @description Seznam hlasování pro daný termín */
            records: components["schemas"]["UserRecord"][];
        };
        Event: {
            /** @description Jedinečné ID události */
            id: number;
            /** @description Název události */
            title: string;
            /** @description Místo konání události (volitelné) */
            location?: string;
            /** @description Seznam možných termínů s hlasováními */
            dates: components["schemas"]["DateRecord"][];
        };
        EventsListResponse: {
            /** @description Seznam všech událostí */
            items: components["schemas"]["Event"][];
        };
        CreateEventRequest: {
            /** @description Název události */
            title: string;
            /** @description Místo konání události (volitelné) */
            location?: string;
            /** @description Seznam možných termínů */
            dates: number[];
        };
        CreateEventResponse: {
            /** @description Zpráva o úspěšném vytvoření události */
            message: string;
        };
        ErrorResponse: {
            /** @description Popis chyby */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
